version: "3.0"
services:
  backend:
    container_name: ligfinder_api_prod
    build: ./backend
    command: uvicorn app.main:app --reload --workers 4 --host 0.0.0.0 --port 3000
    volumes:
      - ./backend:/usr/src/
    expose:
      - 3000
    environment:
      - WATCHFILES_FORCE_POLLING=true
    networks:
      - ligfinder

  database:
    image: pgrouting/pgrouting
    container_name: db_ligfinder_prod
    volumes:
      - ./database/dumps:/var/lib/postgresql/dumps
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=XXX_POSTGRES_PASSWORD_XXX
      - POSTGRES_DB=ligfinder
    networks:
      - ligfinder

  frontend:
    container_name: frontend_ligfinder_prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      - VUE_APP_API_BASE_URL = "/api/"
    ports:
      - 9000:80
    networks:
      - ligfinder

volumes:
  pgdata:

networks:
  ligfinder:
    driver: bridge
