version: "3.0"
services:
  api:
    # container_name: ligfinder_api_dev
    # build: ./backend
    image: orttak/ligfinder_api_prod
    command: uvicorn app.main:app --reload --workers 4 --host 0.0.0.0 --port 3000
    volumes:
      - ./backend:/usr/src/
    # expose:
    #   - 3000
    ports:
      - 3000:3000
    environment:
      - WATCHFILES_FORCE_POLLING=true
    networks:
      - ligfinder_v2

  database:
    image: kartoza/postgis:15-3.3
    container_name: db_ligfinder
    volumes:
      - ./database/dumps:/var/lib/postgresql/dumps
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=agora
      - POSTGRES_USER=agora
      - POSTGRES_PASS=agora
      - FORCE_SSL=FALSE
    networks:
      - ligfinder_v2

  frontend:
    container_name: frontend_ligfinder_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - VUE_APP_API_BASE_URL = "/api/"
    ports:
      - 8080:8080
    networks:
      - ligfinder_v2

volumes:
  pgdata:

networks:
  ligfinder_v2:
    driver: bridge
