version: "3.0"
services:
  api:
    container_name: fastapi-ligfinder-dev-2
    build: ./backend
    command: uvicorn app.main:app --reload --workers 2 --host 0.0.0.0 --port 3000
    volumes:
      - ./backend:/usr/src/
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - WATCHFILES_FORCE_POLLING=true
    networks:
      - ligfinder

  database:
    image: pgrouting/pgrouting
    container_name: db_ligfinder
    volumes:
      - ./database/dumps:/var/lib/postgresql/dumps
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=XXX_POSTGRES_PASSWORD_XXX
      - POSTGRES_DB=ligfinder
    networks:
      - ligfinder

  frontend:
    container_name: frontend_ligfinder-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - VUE_APP_API_BASE_URL = "/api/"
    ports:
      - 8080:8080
    networks:
      - ligfinder

volumes:
  pgdata:

networks:
  ligfinder:
    driver: bridge
