version: "3.3"

services:
  api:
    container_name: fastapi-ligfinder-3
    # image: lig-fastapi_api
    build: .
    command: uvicorn app.main:app --reload --workers 4 --host 0.0.0.0 --port 3000
    volumes:
      - .:/usr/src/
    expose:
      - 3000
    ports:
      - 3000:3000
    # environment:
    #   - DATABASE_URL=postgresql://hello_fastapi:hello_fastapi@db/hello_fastapi_dev

networks:
  ligfinder:
    external: true
